[profile.default]
src = "."
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.ci]
fuzz = { runs = 256 }
invariant = { runs = 256 }

[profile.gas]
# 가스 리포트를 위한 설정
gas_reports = ["*"]


